core-identity-uri: ${SERVICE_SCHEME}://${CORE_IDENTITY_HOST}:${CORE_IDENTITY_PORT}
core-storage-uri: ${SERVICE_SCHEME}://${CORE_STORAGE_HOST}:${CORE_STORAGE_PORT}
core-ai-uri: ${SERVICE_SCHEME}://${CORE_AI_HOST}:${CORE_AI_PORT}


server:
  port: ${SERVICE_PORT}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          jwk-set-uri: ${AUTH_SERVER}/oauth2/jwks
  #          issuer-uri: ${AUTH_SERVER}
  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=legalcase
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: legalcase
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: legalcase
    table: flyway_profile_history
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /api/legalcase/v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    enabled: true
    path: /api/legalcase/swagger-ui.html

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:INFO}
    com.ginkgooai: ${LOG_LEVEL_GINKGOOAI:DEBUG} 